require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/user_abouts", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # UserAbout. As you add validations to UserAbout, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      UserAbout.create! valid_attributes
      get user_abouts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      user_about = UserAbout.create! valid_attributes
      get user_about_url(user_about)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_user_about_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      user_about = UserAbout.create! valid_attributes
      get edit_user_about_url(user_about)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new UserAbout" do
        expect {
          post user_abouts_url, params: { user_about: valid_attributes }
        }.to change(UserAbout, :count).by(1)
      end

      it "redirects to the created user_about" do
        post user_abouts_url, params: { user_about: valid_attributes }
        expect(response).to redirect_to(user_about_url(UserAbout.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new UserAbout" do
        expect {
          post user_abouts_url, params: { user_about: invalid_attributes }
        }.to change(UserAbout, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post user_abouts_url, params: { user_about: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested user_about" do
        user_about = UserAbout.create! valid_attributes
        patch user_about_url(user_about), params: { user_about: new_attributes }
        user_about.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the user_about" do
        user_about = UserAbout.create! valid_attributes
        patch user_about_url(user_about), params: { user_about: new_attributes }
        user_about.reload
        expect(response).to redirect_to(user_about_url(user_about))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        user_about = UserAbout.create! valid_attributes
        patch user_about_url(user_about), params: { user_about: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested user_about" do
      user_about = UserAbout.create! valid_attributes
      expect {
        delete user_about_url(user_about)
      }.to change(UserAbout, :count).by(-1)
    end

    it "redirects to the user_abouts list" do
      user_about = UserAbout.create! valid_attributes
      delete user_about_url(user_about)
      expect(response).to redirect_to(user_abouts_url)
    end
  end
end
