# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Loginwithinvalidpassword' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    sleep(1)
    @driver.quit
  end
  it 'visit root_path before authorizing' do
    @driver.get('localhost:3000/')
    expect(@driver.find_element(:css, '.alert').text).to eq("You need to sign in or sign up before continuing.")
  end

  it 'reg with incorrect passwords' do
    @driver.find_element(:css, '.sign_in').click
        sleep(1)
        @driver.find_element(:id, 'user_email').send_keys('gav@example.com')
        @driver.find_element(:id, 'user_password').send_keys('897654')
        @driver.find_element(:id, 'user_password_confirmation').send_keys('8976547')
        @driver.find_element(:name, 'commit').click
        expect(@driver.find_element(:xpath, '//li').text).to eq("Password confirmation doesn't match Password")
  end

  it 'reg with short password' do
    @driver.find_element(:css, '.sign_in').click
        sleep(1)
        @driver.find_element(:id, 'user_email').send_keys('gav2@example.com')
        @driver.find_element(:id, 'user_password').send_keys('8976')
        @driver.find_element(:id, 'user_password_confirmation').send_keys('8976')
        @driver.find_element(:name, 'commit').click
        expect(@driver.find_element(:xpath, '//li').text).to eq("Password is too short (minimum is 6 characters)")
  end

  it 'reg succesfull' do
    @driver.find_element(:css, '.sign_in').click
    sleep(1)
    @driver.find_element(:id, 'user_email').send_keys('gav2@example.com')
    @driver.find_element(:id, 'user_password').send_keys('123456')
    @driver.find_element(:id, 'user_password_confirmation').send_keys('123456')
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:xpath, '//h1').text).to eq("Матчи")
  end


end
